app:
  - changed-files:
    - any-glob-to-any-file: 'app/**/*'

workers:
  - changed-files:
    - any-glob-to-any-file: 'workers/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
      - '**/package.json'

ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'scripts/**/*'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

ui:
  - changed-files:
    - any-glob-to-any-file:
      - 'app/components/**/*'
      - 'app/features/**/*'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - '**/__tests__/**/*'
      - '**/*.test.ts'
      - '**/*.spec.ts'

i18n:
  - changed-files:
    - any-glob-to-any-file: 'app/locales/**/*'

supabase:
  - changed-files:
    - any-glob-to-any-file: 'supabase/**/*'

config:
  - changed-files:
    - any-glob-to-any-file:
      - 'nuxt.config.ts'
      - 'app.config.ts'
      - 'vitest.config.ts'
      - 'tailwind.config.ts'
      - 'tsconfig.json'
      - '.releaserc.json'
      - 'commitlint.config.js'
      - 'renovate.json'
      - 'eslint.config.*'
      - '.prettierrc*'
      - '.nvmrc'
