name: Enhancement
description: Suggest an improvement to an existing feature
title: "[Enhancement]: "
labels: ["type:enhancement", "status:inbox"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an enhancement! This is for improvements to existing features.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which existing feature would you like to enhance?
      multiple: false
      options:
        - Tasks/Quests
        - Hideout
        - Maps
        - Team Features
        - Traders
        - Needed Items
        - Settings
        - API
        - Other
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: How does the feature currently work?
      placeholder: Currently, when I...
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Enhancement
      description: How would you like it to work instead?
      placeholder: It would be better if...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this enhancement?
      placeholder: This would improve...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Examples
      description: If applicable, add screenshots or examples.
      placeholder: Drag and drop images here or paste URLs
    validations:
      required: false

  - type: input
    id: discord
    attributes:
      label: Discord Handle (Optional)
      description: Your Discord username if you'd like to discuss further
      placeholder: username#1234
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the enhancement.
    validations:
      required: false
